# Generated by Django 3.2.12 on 2022-04-12 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='social_github',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='social_linkedin',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='social_twitter',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='social_youtube',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
