# Generated by Django 3.2.12 on 2022-04-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_supplier_supplier'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roll',
            new_name='Role',
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
