# Generated by Django 3.2.12 on 2022-04-16 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220415_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='roll',
            new_name='role',
        ),
    ]
