# Generated by Django 3.2.12 on 2022-04-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220420_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoposter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='PhotoPoster/'),
        ),
    ]
