# Generated by Django 3.2.12 on 2022-04-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220422_0624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photoposter',
            old_name='image',
            new_name='photoimage',
        ),
        migrations.AddField(
            model_name='garment',
            name='garmentImage',
            field=models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='garments/'),
        ),
        migrations.AddField(
            model_name='premise',
            name='premiseImage',
            field=models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='premises/'),
        ),
    ]
