# Generated by Django 3.2.12 on 2022-04-23 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20220423_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='roll',
        ),
    ]
