# Generated by Django 3.2.12 on 2022-05-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_garment_timeduration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='profile_image',
            field=models.FileField(blank=True, default='profiles/user-default.png', null=True, upload_to='profiles/'),
        ),
    ]
