# Generated by Django 3.2.12 on 2022-05-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_supplier_mobileno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='mobileNo',
            field=models.IntegerField(max_length=10, null=True, unique=True),
        ),
    ]
