# Generated by Django 3.2.12 on 2022-05-31 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_supplier_mobileno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='mobileNo',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Enter Valid Mobile No', regex='^(05)\\d{9}$')]),
        ),
    ]
