# Generated by Django 3.2.12 on 2022-06-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20220531_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='profile_image',
            field=models.FileField(blank=True, default='profiles/user-default.png', null=True, upload_to='static/images/profiles/'),
        ),
    ]
