export const UserActionType = {
    USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
    USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
    
    USER_LOGOUT: "USER_LOGOUT",
    
    USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
    USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
    USER_REGISTER_FAIL: "USER_REGISTER_FAIL",
    
    USER_LIST_REQUEST: "USER_LIST_REQUEST",
    USER_LIST_SUCCESS: "USER_LIST_SUCCESS",
    USER_LIST_FAIL: "USER_LIST_FAIL",

    GET_CUSTOMERS_DATA : "GET_CUSTOMERS_DATA ",
    GET_CUSTOMERS_FAIL : "GET_CUSTOMERS_FAIL",

    GET_AGENCIES_DATA : "GET_AGENCIES_DATA ",
    GET_AGENCIES_FAIL: "GET_AGENCIES_FAIL",
    
    GET_MYTASKS_SUCCESS: "GET_MYTASKS_SUCCESS",
    GET_MYTASKS_FAIL: "GET_MYTASKS_FAIL",
    
}