
export const UserActionType = {
    USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
    USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAIL: "USER_LOGIN_FAIL",

    USER_LOGOUT: "USER_LOGOUT",

    USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
    USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
    USER_REGISTER_FAIL: "USER_REGISTER_FAIL",

    USER_LIST_REQUEST: "USER_LIST_REQUEST",
    USER_LIST_SUCCESS: "USER_LIST_SUCCESS",
    USER_LIST_FAIL: "USER_LIST_FAIL",

    GET_SUPPLIERS_SUCCESS: "GET_SUPPLIERS_SUCCESS",
    GET_SUPPLIERS_FAIL: "GET_SUPPLIERS_FAIL",

    GET_CUSTOMERS_SUCCESS: "GET_CUSTOMERS_SUCCESS ",
    GET_CUSTOMERS_FAIL: "GET_CUSTOMERS_FAIL",

    GET_AGENCIES_SUCCESS: "GET_AGENCIES_SUCCESS ",
    GET_AGENCIES_FAIL: "GET_AGENCIES_FAIL",

    GET_WORKERS_SUCCESS: "GET_WORKERS_SUCCESS ",
    GET_WORKERS_FAIL: "GET_WORKERS_FAIL",

    LIST_MODEL_SUCCESS: "LIST_MODEL_SUCCESS",
    LIST_MODEL_FAIL: "LIST_MODEL_FAIL",


    GET_MYTASKS_SUCCESS: "GET_MYTASKS_SUCCESS",
    GET_MYTASKS_FAIL: "GET_MYTASKS_FAIL",

    ADD_TASK_SUCCESS: "ADD_TASK_SUCCESS",
    ADD_TASK_FAIL: "ADD_TASK_FAIL",

    // LIST_TASKS_SUCCESS: "LIST_TASKS_SUCCESS",
    // LIST_TASKS_FAIL: "LIST_TASKS_FAIL",
    GET_MYGARMENTS_SUCCESS: "GET_MYGARMENTS_SUCCESS",
    GET_MYGARMENTS_FAIL: "GET_MYGARMENTS_FAIL",

    ADD_GARMENT_SUCCESS: "ADD_GARMENT_SUCCESS",
    ADD_GARMENT_FAIL: "ADD_GARMENT_FAIL",

    GET_MYGADGETS_SUCCESS: "GET_MYGADGETS_SUCCESS",
    GET_MYGADGETS_FAIL: "GET_MYGADGETS_FAIL",

    ADD_GADGET_SUCCESS: "ADD_GADGET_SUCCESS",
    ADD_GADGET_FAIL: "ADD_GADGET_FAIL",

    LIST_PHOTOPOSTER_SUCCESS: "LIST_PHOTOPOSTER_SUCCESS",
    LIST_PHOTOPOSTER_FAIL: "LIST_PHOTOPOSTER_FAIL",

    ADD_PHOTOPOSTER_SUCCESS: "ADD_PHOTOPOSTER_SUCCESS",
    ADD_PHOTOPOSTER_FAIL: "ADD_PHOTOPOSTER_FAIL",

    // ADD_MODEL_SUCCESS: "ADD_MODEL_SUCCESS",
    // ADD_MODEL_FAIL: "ADD_MODEL_FAIL",

    GET_WORKER_SUCCESS: 'GET_WORKER_SUCCESS',
    GET_WORKER_FAIL: 'GET_WORKER_FAIL',

    GET_SUPPLIER_SUCCESS: 'GET_SUPPLIER_SUCCESS',
    GET_SUPPLIER_FAIL: 'GET_SUPPLIER_FAIL',

    GET_CUSTOMER_SUCCESS: 'GET_CUSTOMER_SUCCESS',
    GET_CUSTOMER_FAIL: 'GET_CUSTOMER_FAIL',

    GET_AGENCY_SUCCESS: 'GET_AGENCY_SUCCESS',
    GET_AGENCY_FAIL: 'GET_AGENCY_FAIL',

    GET_MODEL_SUCCESS: 'GET_MODEL_SUCCESS',
    GET_MODEL_FAIL: 'GET_MODEL_FAIL',

    EDIT_SUPPLIER_SUCCESS: 'EDIT_SUPPLIER_SUCCESS',
    EDIT_SUPPLIER_FAIL: 'EDIT_SUPPLIER_FAIL',

    EDIT_CUSTOMER_SUCCESS: 'EDIT_CUSTOMER_SUCCESS',
    EDIT_CUSTOMER_FAIL: 'EDIT_CUSTOMER_FAIL',

    EDIT_AGENCY_SUCCESS: 'EDIT_AGENCY_SUCCESS',
    EDIT_AGENCY_FAIL: 'EDIT_AGENCY_FAIL',

    EDIT_WORKER_SUCCESS: 'EDIT_WORKER_SUCCESS',
    EDIT_WORKER_FAIL: 'EDIT_WORKER_FAIL',

    EDIT_MODEL_SUCCESS: 'EDIT_MODEL_SUCCESS',
    EDIT_MODEL_FAIL: 'EDIT_MODEL_FAIL',


}