import { List } from "@mui/material";

export const UserActionType = {
    USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
    USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAIL: "USER_LOGIN_FAIL",

    USER_LOGOUT: "USER_LOGOUT",

    USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
    USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
    USER_REGISTER_FAIL: "USER_REGISTER_FAIL",

    USER_LIST_REQUEST: "USER_LIST_REQUEST",
    USER_LIST_SUCCESS: "USER_LIST_SUCCESS",
    USER_LIST_FAIL: "USER_LIST_FAIL",

    GET_CUSTOMERS_DATA: "GET_CUSTOMERS_DATA ",
    GET_CUSTOMERS_FAIL: "GET_CUSTOMERS_FAIL",

    GET_AGENCIES_DATA: "GET_AGENCIES_DATA ",
    GET_AGENCIES_FAIL: "GET_AGENCIES_FAIL",

    GET_MYTASKS_SUCCESS: "GET_MYTASKS_SUCCESS",
    GET_MYTASKS_FAIL: "GET_MYTASKS_FAIL",

    ADD_TASK_SUCCESS: "ADD_TASK_SUCCESS",
    ADD_TASK_FAIL: "ADD_TASK_FAIL",

    // LIST_TASKS_SUCCESS: "LIST_TASKS_SUCCESS",
    // LIST_TASKS_FAIL: "LIST_TASKS_FAIL",
    GET_MYGARMENTS_SUCCESS: "GET_MYGARMENTS_SUCCESS",
    GET_MYGARMENTS_FAIL: "GET_MYGARMENTS_FAIL",

    ADD_GARMENT_SUCCESS: "ADD_GARMENT_SUCCESS",
    ADD_GARMENT_FAIL: "ADD_GARMENT_FAIL",

    GET_MYGADGETS_SUCCESS: "GET_MYGADGETS_SUCCESS",
    GET_MYGADGETS_FAIL: "GET_MYGADGETS_FAIL",

    ADD_GADGET_SUCCESS: "ADD_GADGET_SUCCESS",
    ADD_GADGET_FAIL: "ADD_GADGET_FAIL",

    // ADD_PHOTOPOSTER_SUCCESS: "ADD_PHOTOPOSTER_SUCCESS",
    // ADD_PHOTOPOSTER_FAIL: "ADD_PHOTOPOSTER_FAIL",

    LIST_PHOTOPOSTER_SUCCESS: "LIST_PHOTOPOSTER_SUCCESS",
    LIST_PHOTOPOSTER_FAIL: "LIST_PHOTOPOSTER_FAIL",

    // ADD_MODEL_SUCCESS: "ADD_MODEL_SUCCESS",
    // ADD_MODEL_FAIL: "ADD_MODEL_FAIL",

    LIST_MODEL_SUCCESS: "LIST_MODEL_SUCCESS",
    LIST_MODEL_FAIL: "LIST_MODEL_FAIL",
}